# COMP5318 Assignment 1: Rice Classification

##### Group number: 92
##### Student 1 SID: 550455842
##### Student 2 SID: ...  
##### Student 3 SID: ...

## **1. Data Pre-processing**

### 1.1 Libraries

In [1]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from warnings import simplefilter

### 1.2 Ignore future warnings

In [8]:
simplefilter(action='ignore', category=FutureWarning)

### 1.3 Read dataset

In [ ]:
rice_dataset = pd.read_csv('rice-final2.csv', na_values='?')

### 1.4 Filling in the missing attribute values

#### 1.4.1 Check values

In [ ]:
rice_dataset.head()

,Area,Perimiter,Major_Axis_Length,Minor_Axis_Length,Eccentricity,Convex_Area,Extent,class
0,12573.0,461.466003,192.903351,84.572075,0.898772,12893.0,0.550433,class2
1,12845.0,464.121002,194.332214,85.524338,0.897952,13125.0,0.774962,class2
2,14055.0,488.748993,207.751755,87.250328,0.907536,14484.0,0.550076,class1
3,14412.0,490.324005,207.476135,89.689514,0.901735,14703.0,0.598853,class1
4,14658.0,477.117004,189.566635,99.997780,0.849551,15048.0,0.649504,class2

#### 1.4.2 Check null values of each columns

In [38]:
rice_dataset.isnull().sum()

Area                 4
Perimiter            4
Major_Axis_Length    5
Minor_Axis_Length    3
Eccentricity         6
Convex_Area          5
Extent               2
class                0
dtype: int64

#### 1.4.3 Filling in the missing attribute values

In [39]:
imputer =  SimpleImputer(strategy='mean')

feature_cols = rice_dataset.columns.drop('class')

rice_imputed = rice_dataset.copy()

rice_imputed[feature_cols] = imputer.fit_transform(rice_dataset[feature_cols])

In [41]:
rice_imputed.isnull().sum()

Area                 0
Perimiter            0
Major_Axis_Length    0
Minor_Axis_Length    0
Eccentricity         0
Convex_Area          0
Extent               0
class                0
dtype: int64

### 1.5 Normalising	the	data

#### 1.5.1 Check min and max values

In [50]:
rice_imputed[feature_cols].min()

Area                 7943.000000
Perimiter             359.100006
Major_Axis_Length     145.264465
Minor_Axis_Length      63.344753
Eccentricity            0.799511
Convex_Area          8080.000000
Extent                  0.511160
dtype: float64

In [49]:
rice_imputed[feature_cols].max()

Area                 17948.000000
Perimiter              548.445984
Major_Axis_Length      238.435089
Minor_Axis_Length      107.542450
Eccentricity             0.934006
Convex_Area          18322.000000
Extent                   0.839661
dtype: float64

#### 1.5.2 normalising

In [44]:
sclaer = MinMaxScaler()

feature_cols_imputed = rice_imputed.columns.drop('class')

rice_normalised_imputed = rice_imputed.copy()

rice_normalised_imputed[feature_cols_imputed] = sclaer.fit_transform(rice_imputed[feature_cols_imputed])

#### 1.5.3 Check min and max values again

In [47]:
rice_normalised_imputed[feature_cols_imputed].min()

Area                 0.0
Perimiter            0.0
Major_Axis_Length    0.0
Minor_Axis_Length    0.0
Eccentricity         0.0
Convex_Area          0.0
Extent               0.0
dtype: float64

In [48]:
rice_normalised_imputed[feature_cols_imputed].max()

Area                 1.0
Perimiter            1.0
Major_Axis_Length    1.0
Minor_Axis_Length    1.0
Eccentricity         1.0
Convex_Area          1.0
Extent               1.0
dtype: float64

### 1.6 Changing the class values

#### 1.6.1 Check values

In [52]:
rice_normalised_imputed['class'].unique()

array(['class2', 'class1'], dtype=object)

#### 1.6.2 Mapping

In [51]:
rice_encoded_normalised_imputed = rice_normalised_imputed.copy()

rice_encoded_normalised_imputed['class'] = rice_encoded_normalised_imputed['class'].map({
    'class1': 0,
    'class2': 1
})

#### 1.6.3 Check values again

In [54]:
rice_encoded_normalised_imputed['class'].unique()

array([1, 0])

### 1.7 Print the first	10 rows of the pre-processed dataset

In [21]:
# Print first ten rows of pre-processed dataset to 4 decimal places as per assignment spec
# A function is provided to assist

def print_data(X, y, n_rows=10):
    """Takes a numpy data array and target and prints the first ten rows.
    
    Arguments:
        X: numpy array of shape (n_examples, n_features)
        y: numpy array of shape (n_examples)
        n_rows: numpy of rows to print
    """
    for example_num in range(n_rows):
        for feature in X[example_num]:
            print("{:.4f}".format(feature), end=",")

        if example_num == len(X)-1:
            print(y[example_num],end="")
        else:
            print(y[example_num])

In [60]:
X = rice_encoded_normalised_imputed.drop(columns=['class']).to_numpy()
y = rice_encoded_normalised_imputed['class'].to_numpy()

print(X, y)

[[0.46276862 0.54062937 0.511308   ... 0.73802366 0.46992775 0.11955211]
 [0.48995502 0.55465132 0.52664399 ... 0.73192824 0.49257957 0.80304787]
 [0.61089455 0.68472005 0.67067587 ... 0.80318891 0.6252685  0.11846508]
 ...
 [0.69975012 0.80824013 0.88173494 ... 0.96167029 0.69000195 0.91686252]
 [0.28835582 0.29972122 0.23711135 ... 0.49679629 0.30706893 0.43393018]
 [0.73893053 0.79053698 0.7942185  ... 0.8393834  0.73413396 0.20958212]] [1 1 0 ... 0 1 0]

### 1.8 Another dataset

In [6]:
test_dataset = pd.read_csv('test-before.csv', na_values='?')

In [7]:
test_dataset.head()

      a1      a2      a3     a4     a5      a6   class
0   5.88  0.4874  0.5410  1.515  16.55  0.3458  class1
1  76.47  0.7286  0.6721  1.919  13.00  0.3308  class1
2  29.41  0.5879     NaN  0.000   0.00  0.5082  class1
3  29.41  0.5477  0.6148  2.626   0.00  0.5365  class1
4  17.65  0.7940  0.6230  3.636  28.96     NaN  class2

In [8]:
test_dataset.isnull().sum()

a1       1
a2       3
a3       2
a4       2
a5       1
a6       3
class    0
dtype: int64

In [9]:
imputer =  SimpleImputer(strategy='mean')

feature_cols = test_dataset.columns.drop('class')

test_imputed = test_dataset.copy()

test_imputed[feature_cols] = imputer.fit_transform(test_dataset[feature_cols])

In [10]:
test_imputed.isnull().sum()

a1       0
a2       0
a3       0
a4       0
a5       0
a6       0
class    0
dtype: int64

In [11]:
test_imputed[feature_cols].min()

a1    0.0
a2    0.0
a3    0.0
a4    0.0
a5    0.0
a6    0.0
dtype: float64

In [12]:
test_imputed[feature_cols].max()

a1    94.7200
a2     0.9749
a3     1.0000
a4     7.2860
a5    63.8000
a6     5.6450
dtype: float64

In [13]:
sclaer = MinMaxScaler()

feature_cols_imputed = test_imputed.columns.drop('class')

test_normalised_imputed = test_imputed.copy()

test_normalised_imputed[feature_cols_imputed] = sclaer.fit_transform(test_imputed[feature_cols_imputed])

In [14]:
test_normalised_imputed[feature_cols_imputed].min()

a1    0.0
a2    0.0
a3    0.0
a4    0.0
a5    0.0
a6    0.0
dtype: float64

In [15]:
test_normalised_imputed[feature_cols_imputed].max()

a1    1.0
a2    1.0
a3    1.0
a4    1.0
a5    1.0
a6    1.0
dtype: float64

In [16]:
test_normalised_imputed['class'].unique()

array(['class1', 'class2'], dtype=object)

In [17]:
test_encoded_normalised_imputed = test_normalised_imputed.copy()

test_encoded_normalised_imputed['class'] = test_encoded_normalised_imputed['class'].map({
    'class1': 0,
    'class2': 1
})

In [18]:
test_encoded_normalised_imputed['class'].unique()

array([0, 1])

In [23]:
X = test_encoded_normalised_imputed.drop(columns=['class']).to_numpy()
y = test_encoded_normalised_imputed['class'].to_numpy()

print(X, y)

[[6.20777027e-02 4.99948713e-01 5.41000000e-01 2.07933022e-01
  2.59404389e-01 6.12577502e-02]
 [8.07326858e-01 7.47358703e-01 6.72100000e-01 2.63381828e-01
  2.03761755e-01 5.86005314e-02]
 [3.10494088e-01 6.03036209e-01 4.18737681e-01 0.00000000e+00
  0.00000000e+00 9.00265722e-02]
 ...
 [3.10494088e-03 8.14442507e-01 6.88500000e-01 5.68350261e-02
  9.20376176e-03 2.39858282e-01]
 [6.20777027e-04 5.41183711e-01 4.75400000e-01 0.00000000e+00
  5.67554859e-03 8.23737821e-02]
 [1.86338682e-03 5.51543748e-01 5.08200000e-01 1.80208619e-02
  5.34952978e-03 4.53852967e-01]] [0 0 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1
 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 0 0
 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0
 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1
 1 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0]

## **2. Build Classifiers**

- Part 1:  Logistic Regression, Naïve Bayes
- Part 2:  KNN, Decision Tree, Ada Boost, Gradient Boost, Random Forest, SVM

### Part 1: Cross-validation without parameter tuning

In [51]:
## Setting the 10 fold stratified cross-validation
cvKFold=StratifiedKFold(n_splits=10, shuffle=True, random_state=0)

# The stratified folds from cvKFold should be provided to the classifiers

In [ ]:
# Logistic Regression

In [ ]:
# Naïve Bayes

### Part 1 Results

In [ ]:
# Print results for each classifier in part 1 to 4 decimal places here:
print("LogR average cross-validation accuracy: ")
print("NB average cross-validation accuracy: ")

### Part 2: Cross-validation with parameter tuning

In [ ]:
# KNN 
# parameters you may consider
k = [1, 3, 5, 7]
p = [1, 2]

In [ ]:
# Decision Tree 
# parameters you may consider
max_depth = [3, 5, 7, 10]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]

In [ ]:
# Ada Boost
# parameters you may consider
n_estimators = [50, 100, 150]
learning_rate = [0.1, 0.2, 0.3, 0.5]

In [ ]:
# Gradient Boost
# parameters you may consider
max_depth = [1, 3, 5, 7]
n_estimators = [50, 100, 150]
learning_rate = [0.1, 0.2, 0.3, 0.5]

In [ ]:
# Random Forest
# You should use RandomForestClassifier from sklearn.ensemble with information gain and max_features set to ‘sqrt’.
# parameters you may consider
n_estimators = [10, 30, 60, 100]
max_leaf_nodes = [6, 12]

In [ ]:
# SVM
# parameters you may consider
C = [0.01, 0.1, 1, 5]
gamma = [0.01, 0.1, 1, 10]
# optional
kernel = []

### Part 2: Results

In [ ]:
# Perform Grid Search with 10-fold stratified cross-validation (GridSearchCV in sklearn). 
# The stratified folds from cvKFold should be provided to GridSearchV

# This should include using train_test_split from sklearn.model_selection with stratification and random_state=0
# Print results for each classifier here. All the reported results should be printed to 4 decimal places except for the integers such as "k", "p", n_estimators" and "max_leaf_nodes".

# example printing:
print("KNN best k: ")
print("KNN best p: ")
print("KNN cross-validation accuracy: ")
print("KNN test set accuracy: ")

...

print("RF best n_estimators: ")
print("RF best max_leaf_nodes: ")
print("RF cross-validation accuracy: ")
print("RF test set accuracy: ")
print("RF test set macro average F1: ")
print("RF test set weighted average F1: ")

KNN best k:
KNN best p:
KNN cross-validation accuracy:
KNN test set accuracy:

RF best n_estimators:
RF best max_leaf_nodes:
RF cross-validation accuracy:
RF test set accuracy:
RF test set macro average F1:
RF test set weighted average F1:

### Test your code

In [ ]:
#load the test dataset to test out your model

## **3. Reflection and Discussion**

## **AI Acknowledgement**